# Generated by Django 6.1 on 2026-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=20)),
                ('price_per_gallon', models.DecimalField(decimal_places=4, max_digits=6)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('highway', models.CharField(blank=True, db_index=True, max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuelroute_f_latitud_24ebfc_idx')],
            },
        ),
    ]
