# Generated by Django 6.1 on 2026-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_precision',
            field=models.CharField(choices=[('exit', 'Exit interchange (Overpass/OSM)'), ('city', 'City centroid (gazetteer)')], default='city', max_length=10),
        ),
    ]
